/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package uno.anahata.nb.ai;

import lombok.extern.slf4j.Slf4j;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//uno.anahata.nb.ai//AnahataNavigator//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "AnahataNavigatorTopComponent",
        iconBase = "icons/anahata_16.png",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "navigator", openAtStartup = true)
@ActionID(category = "Window", id = "uno.anahata.nb.ai.AnahataNavigatorTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_AnahataNavigatorAction",
        preferredID = "AnahataNavigatorTopComponent"
)
@Messages({
    "CTL_AnahataNavigatorAction=AnahataNavigator",
    "CTL_AnahataNavigatorTopComponent=AnahataNavigator Window",
    "HINT_AnahataNavigatorTopComponent=This is a AnahataNavigator window"
})
@Slf4j
public final class AnahataNavigatorTopComponent extends TopComponent {

    public AnahataNavigatorTopComponent() {
        initComponents();
        //setName(Bundle.CTL_AnahataNavigatorTopComponent());
        //setToolTipText(Bundle.HINT_AnahataNavigatorTopComponent());
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpenAnahata = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(OpenAnahata, org.openide.util.NbBundle.getMessage(AnahataNavigatorTopComponent.class, "AnahataNavigatorTopComponent.OpenAnahata.text")); // NOI18N
        OpenAnahata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenAnahataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(OpenAnahata)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(OpenAnahata)
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void OpenAnahataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenAnahataActionPerformed
            AnahataTopComponent tc = new AnahataTopComponent();
            tc.open();
            
    }//GEN-LAST:event_OpenAnahataActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OpenAnahata;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
